tap "nikitabobko/tap"
brew "bat"
brew "biome"
brew "eza"
brew "fnm"
brew "gh"
brew "git-delta"
brew "lazygit"
brew "mas"
brew "pnpm"
brew "starship"
brew "stow"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "1password"
cask "aerospace"
cask "brave-browser"
cask "claude-code"
cask "cleanshot"
cask "cursor"
cask "font-jetbrains-mono-nerd-font"
cask "orbstack"
cask "protonvpn"
cask "raycast"
cask "readdle-spark"
cask "signal"
cask "spotify"
cask "warp"
mas "1Password for Safari", id: 1569813296
mas "Bear", id: 1091189122
mas "Pixelmator Pro", id: 1289583905
