tap "nikitabobko/tap"
tap "oven-sh/bun"
brew "agent-browser"
brew "biome"
brew "eza"
brew "gh"
brew "mas"
brew "node"
brew "prettier"
brew "starship"
brew "stow"
brew "uv"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "oven-sh/bun/bun"
cask "nikitabobko/tap/aerospace"
cask "claude-code"
cask "cleanshot"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "helium-browser"
cask "orbstack"
cask "protonvpn"
cask "raycast"
cask "signal"
cask "spotify"
cask "visual-studio-code"
mas "1Password for Safari", id: 1569813296
mas "Final Cut Pro", id: 424389933
mas "Logic Pro", id: 634148309
mas "Proton Pass for Safari", id: 6502835663
