start-at-login = true

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[workspace-to-monitor-force-assignment]
'1' = '1'
'2' = '1'
'3' = '1'
'4' = '1'

'5' = '2'
'6' = '2'
'7' = '2'
'8' = '2'

[mode.main.binding]
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-a = 'workspace 1'
alt-s = 'workspace 2'
alt-d = 'workspace 3'
alt-f = 'workspace 4'

alt-z = 'workspace 5'
alt-x = 'workspace 6'
alt-c = 'workspace 7'
alt-v = 'workspace 8'

alt-shift-a = 'move-node-to-workspace 1'
alt-shift-s = 'move-node-to-workspace 2'
alt-shift-d = 'move-node-to-workspace 3'
alt-shift-f = 'move-node-to-workspace 4'

alt-shift-z = 'move-node-to-workspace 5'
alt-shift-x = 'move-node-to-workspace 6'
alt-shift-c = 'move-node-to-workspace 7'
alt-shift-v = 'move-node-to-workspace 8'

alt-tab = 'workspace-back-and-forth'

alt-shift-i = 'fullscreen'
alt-shift-q = ['mode service', 'reload-config', 'mode main']

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

# ------------ Monitor 1 ------------

# --- Workspace 1 ---

# Todoist (supports both Electron app and Safari Web App)
[[on-window-detected]]
if.app-name-regex-substring = 'Todoist'
run = 'move-node-to-workspace 1'

# --- Workspace 2 ---

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
# Cursor
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = 'move-node-to-workspace 2'

# --- Workspace 3 ---

# Slack (supports both Electron app and Safari Web App)
[[on-window-detected]]
if.app-name-regex-substring = 'Slack'
run = 'move-node-to-workspace 3'

# --- Workspace 4 ---

# ------------ Monitor 2 ------------

# --- Workspace 5 ---

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace 5'

# --- Workspace 6 ---

[[on-window-detected]]
if.app-id = 'dev.warp.Warp-Stable'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 6'

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = 'move-node-to-workspace 6'

# --- Workspace 7 ---

[[on-window-detected]]
if.app-id = 'com.readdle.SparkDesktop'
run = 'move-node-to-workspace 7'

# --- Workspace 8 ---

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 8'

# Safari Web Apps Configuration
#
# Safari Web Apps (Add to Dock) have dynamic bundle IDs that change per machine.
# Solution: Use app-name-regex-substring instead of app-id
#
# IMPORTANT: When creating Safari Web Apps, name them consistently across machines:
#   - Todoist → workspace 1
#   - Slack → workspace 3
#
# Debug commands:
#   lsappinfo list | grep -i safari
#   aerospace list-windows --all --format "%{app-name} | %{app-bundle-id}"
