#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

# theme
COLOR_BG=0x782f3448
COLOR_ICON=0xcc8caaee
COLOR_LABEL=0xffffffff
COLOR_OVERLAY=0x40c6d0f5

FONT_LARGE="JetBrainsMono Nerd Font:Bold:16.0"
FONT_MEDIUM="JetBrainsMono Nerd Font:Regular:14.0"
FONT_SMALL="JetBrainsMono Nerd Font:Regular:12.0"
FONT_ICON="sketchybar-app-font:Regular:16.0"

SIZE_MEDIUM=8
SIZE_SMALL=4

# bar
sketchybar --bar position=top height=40 blur_radius=32 color="$COLOR_BG"

# default values
default=(
  padding_left="$SIZE_SMALL"
  padding_right="$SIZE_SMALL"
  icon.padding_left="$SIZE_SMALL"
  icon.padding_right="$SIZE_SMALL"
  label.padding_left="$SIZE_SMALL"
  label.padding_right="$SIZE_SMALL"
  icon.color="$COLOR_ICON"
  label.color="$COLOR_LABEL"
  icon.font="$FONT_LARGE"
  label.font="$FONT_MEDIUM"
)
sketchybar --default "${default[@]}"

# spaces
SPACE_ICONS=("" "" "󰖟" "" "󰭹" "")
for i in "${!SPACE_ICONS[@]}"; do
  sid="$(($i + 1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    background.color="$COLOR_OVERLAY"
    background.corner_radius="$SIZE_MEDIUM"
    background.height=32
    label="$sid"
    label.font="$FONT_SMALL"
    icon.padding_left="$SIZE_MEDIUM"
    label.padding_right="$SIZE_MEDIUM"
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

# left items
sketchybar --add item chevron left \
  --add item front_app left \
  --set front_app icon.font="$FONT_ICON" label.font="$FONT_LARGE" script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

# right items
sketchybar --add item clock right \
  --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

sketchybar --update
